feat: add error handling and exit condition for docker compose pull command

diff --git a/roles/artemis/templates/artemis-docker.sh.j2 b/roles/artemis/templates/artemis-docker.sh.j2
--- a/roles/artemis/templates/artemis-docker.sh.j2
+++ b/roles/artemis/templates/artemis-docker.sh.j2
@@ -46,7 +46,11 @@ function start {
         exit 1
     fi
 
-    docker compose --project-directory "$PROJECT_DIR" -f "$PROJECT_DIR/$COMPOSE_FILE" --env-file "$DOCKER_IMAGE_ENV_FILE" --env-file "$ENV_FILE" pull $artemis_services
+    if ! docker compose --project-directory "$PROJECT_DIR" -f "$PROJECT_DIR/$COMPOSE_FILE" --env-file "$DOCKER_IMAGE_ENV_FILE" --env-file "$ENV_FILE" pull $artemis_services; then
+        echo "Failed to pull Artemis services ($artemis_services) using compose file $COMPOSE_FILE" 1>&2
+        exit 1
+    fi
+
     docker compose --project-directory "$PROJECT_DIR" -f "$PROJECT_DIR/$COMPOSE_FILE" --env-file "$DOCKER_IMAGE_ENV_FILE" --env-file "$ENV_FILE" up -d --no-build --remove-orphans
     
     # Reload Nginx configuration as Nginx may still be running from a previous start. This is necessary to apply the new configuration.
