fixes and minor improvements

diff --git a/roles/storage_backup/templates/backup.sh.j2 b/roles/storage_backup/templates/backup.sh.j2
--- a/roles/storage_backup/templates/backup.sh.j2
+++ b/roles/storage_backup/templates/backup.sh.j2
@@ -6,7 +6,7 @@ prune=false
 function usage {
     cat << HELP
 Usage:
-$(basename $0) [options]
+"$(basename "$0")" [options]
 
 Options:
 -s                          Perform Storage Backup.
@@ -20,7 +20,7 @@ while getopts ":sph" opt; do case ${opt} in
     p ) prune=true;;
     \? ) printf "Invalid Option: -$OPTARG\n\n" 1>&2; usage; exit 1;;
 esac; done
-if [ $OPTIND -eq 1 ]; then printf "Invalid Option: $(basename $0) requires options.\nRun $(basename $0) -h for help.\n" 1>&2; exit 1; fi
+if [ $OPTIND -eq 1 ]; then printf "Invalid Option: %s requires options.\nRun %s -h for help.\n" "$(basename "$0")" "$(basename "$0")" 1>&2; exit 1; fi
 shift $((OPTIND -1))
 
 export BORG_PASSPHRASE={{ storage_backup_password }}
@@ -30,7 +30,7 @@ if [ $prune = true ]; then # Prune old backups
 fi
 
 if [ $storage = true ]; then # Storage Backup
-    borg create -C {{ storage_backup_compression }} "{{ storage_backup_dir }}" "{{ storage_export }}"
+    borg create -C {{ storage_backup_compression }} "{{ storage_backup_dir }}::{hostname}-{now:%Y-%m-%dT%H:%M:%S}" "{{ storage_export }}"
 fi
 
 unset BORG_PASSPHRASE
